"use client";

import * as React from "react";
import { Loader2, Route } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { toast } from "sonner";

type User = { id: number; fullName: string; assignedSpecialtyId: number; scopeAcademicYearId: number | null; scopeTrackId: number | null; scopeGroupId: number | null; scopeCohortGroupId: number | null };
type Item = { id: number; nameAr?: string; yearName?: string; trackNameAr?: string; groupName?: string };
const cls = "flex h-9 w-full rounded-md border border-input bg-background px-3 py-1 text-sm";

export function AcademicPathDialog({ user, onClose, onDone }: { user: User; onClose: () => void; onDone: () => void }) {
  const [institutions, setInstitutions] = React.useState<Item[]>([]); const [specialties, setSpecialties] = React.useState<Item[]>([]); const [years, setYears] = React.useState<Item[]>([]); const [tracks, setTracks] = React.useState<Item[]>([]); const [groups, setGroups] = React.useState<Item[]>([]); const [cohorts, setCohorts] = React.useState<Item[]>([]);
  const [specialtyId, setSpecialtyId] = React.useState(String(user.assignedSpecialtyId)); const [yearId, setYearId] = React.useState(String(user.scopeAcademicYearId ?? "")); const [trackId, setTrackId] = React.useState(String(user.scopeTrackId ?? "")); const [groupId, setGroupId] = React.useState(String(user.scopeGroupId ?? "")); const [cohortId, setCohortId] = React.useState(String(user.scopeCohortGroupId ?? "")); const [saving, setSaving] = React.useState(false);
  React.useEffect(() => { fetch("/api/institutions").then(r => r.json()).then(d => setInstitutions(d.institutions ?? [])); }, []);
  React.useEffect(() => { if (!institutions.length) return; const institutionId = institutions[0].id; fetch(`/api/specialties?institutionId=${institutionId}`).then(r => r.json()).then(d => setSpecialties(d.specialties ?? [])); }, [institutions]);
  React.useEffect(() => { if (!specialtyId) return; Promise.all([fetch(`/api/onboarding/years?specialtyId=${specialtyId}`).then(r => r.json()), fetch(`/api/tracks?specialtyId=${specialtyId}`).then(r => r.json())]).then(([y, t]) => { setYears(y.years ?? []); setTracks(t.tracks ?? []); }); }, [specialtyId]);
  React.useEffect(() => { if (!specialtyId || !yearId) return; fetch(`/api/groups?specialtyId=${specialtyId}&academicYearId=${yearId}${trackId ? `&trackId=${trackId}` : ""}`).then(r => r.json()).then(d => setGroups(d.groups ?? [])); fetch(`/api/cohort?specialtyId=${specialtyId}&academicYearId=${yearId}`).then(r => r.json()).then(d => setCohorts(d.cohorts ?? [])); }, [specialtyId, yearId, trackId]);
  async function save() { if (!specialtyId || !yearId) return toast.error("اختر التخصص والسنة"); if (!window.confirm("سيتم تحديث المحتوى والمجموعات حسب المسار الجديد. هل تريد المتابعة؟")) return; setSaving(true); try { const res = await fetch(`/api/users/${user.id}/academic-path`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ specialtyId: Number(specialtyId), academicYearId: Number(yearId), trackId: trackId ? Number(trackId) : null, groupId: groupId ? Number(groupId) : null, cohortId: cohortId ? Number(cohortId) : null }) }); const data = await res.json(); if (!res.ok) return toast.error(data.error ?? "تعذر التحديث"); toast.success(data.message); onDone(); } finally { setSaving(false); } }
  return <Dialog open onOpenChange={onClose}><DialogContent><DialogHeader><DialogTitle className="flex items-center gap-2"><Route className="w-5 h-5 text-primary" />تغيير المسار الأكاديمي</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">{user.fullName} — سيتم عرض المحتوى وفق الاختيارات الجديدة.</p><div className="grid gap-3">{[["التخصص", specialtyId, setSpecialtyId, specialties, "nameAr"], ["السنة", yearId, setYearId, years, "yearName"], ["الملمح", trackId, setTrackId, tracks, "trackNameAr"], ["المجموعة", groupId, setGroupId, groups, "groupName"], ["الفوج", cohortId, setCohortId, cohorts, "groupName"]].map(([label, value, setter, items, key]) => <div key={String(label)} className="space-y-1"><Label>{String(label)}</Label><select className={cls} value={String(value)} onChange={e => (setter as (v: string) => void)(e.target.value)}><option value="">— اختر —</option>{(items as Item[]).map(i => <option key={i.id} value={i.id}>{String(i[key as keyof Item] ?? i.id)}</option>)}</select></div>)}</div><DialogFooter><Button variant="outline" onClick={onClose}>إلغاء</Button><Button onClick={save} disabled={saving}>{saving && <Loader2 className="w-4 h-4 ml-1 animate-spin" />}حفظ المسار</Button></DialogFooter></DialogContent></Dialog>;
}
